# Generated by Django 2.2 on 2021-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.IntegerField(),
        ),
    ]
