# Generated by Django 2.2 on 2021-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0002_auto_20210715_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='numberOf_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='totalArea',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
