# Generated by Django 2.2 on 2021-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0003_auto_20210715_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='furnish',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='kitchenArea',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='livingArea',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='totalFloor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
