# Generated by Django 2.2 on 2021-07-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0004_auto_20210715_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSell', models.FileField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sellId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Sell.Sell')),
            ],
        ),
    ]
