# Generated by Django 2.2 on 2021-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0005_auto_20210723_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='imageSell',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
