# Generated by Django 2.2 on 2021-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0006_auto_20210727_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='furnish',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='kitchenArea',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='livingArea',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='numberOf_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
