# Generated by Django 2.2 on 2021-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0007_auto_20210728_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='numberOf_rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
