# Generated by Django 2.2 on 2021-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0008_auto_20210728_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='kitchenArea',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='livingArea',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='numberOf_rooms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='totalArea',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='totalFloor',
            field=models.TextField(),
        ),
    ]
