# Generated by Django 2.2 on 2021-07-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0010_auto_20210728_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='headerImage',
            field=models.ImageField(blank=True, default='images/KVARTIRA.png', upload_to='images/'),
        ),
    ]
