# Generated by Django 2.2 on 2021-07-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0012_auto_20210728_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='headerImage',
            field=models.ImageField(default='KVARTIRA.png', upload_to='images/'),
        ),
    ]
