# Generated by Django 2.2 on 2021-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0015_auto_20210728_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='district',
            field=models.TextField(null=True),
        ),
    ]
